extern double *grad, *grad_p;
extern double _Complex *Exobs;
extern double _Complex *Eyobs;
extern double _Complex *Ezobs;
extern double _Complex *rec_ex;
extern double _Complex *delEx_t;
extern double _Complex *delEx_f;
extern double _Complex *delEy_f;
extern double _Complex *delEz_f;
extern double _Complex *Ecal_f;
extern double _Complex *EcalX_b;
extern double _Complex *EcalY_b;
extern double _Complex *EcalZ_b;
extern double _Complex *EcalX_back;
extern double _Complex *EcalY_back;
extern double _Complex *EcalZ_back;
extern double _Complex *EcalX_bb;
extern double _Complex *EcalY_bb;
extern double _Complex *EcalZ_bb;
extern double _Complex *EcalX_ff,*EcalX_ff2,*EcalX_ffL,*EcalX_del;
extern double _Complex *EcalY_ff,*EcalY_ff2,*EcalY_ffL,*EcalY_del;
extern double _Complex *EcalZ_ff,*EcalZ_ff2,*EcalZ_ffL,*EcalZ_del;
extern double *Ex_backwave;
extern double *Gx_back;
extern double *sense;
extern double alpha,scaler;
extern double _Complex k1,k2;
extern FILE *ofer;
