python polar.py
python polar2.py
python polar3.py
python polar4.py
python polar_every.py
python polar_rotation.py
python polar_subplot.py
python timediffseries.py
python model.py
python diff.py
python diff12.py