#!/bin/sh

#メインスクリプト
ifort -o ficticious ../code/parameter.f90 ../code/set.f90 ../code/source.f90 ../code/model.f90 ../code/output.f90 ../code/e_field2.f90 ../code/e_cpml2.f90 ../code/h_field2.f90 ../code/h_cpml2.f90 ../code/main.f90  #-check all -CB -traceback -g
time ./ficticious 

#FFTスクリプト
i=1010
j=`expr $i - 1000`
max=30

while [ $j -le $max ]; do
cp hz$i.d inp1.dat
ifort ../code/parameter.f90 f_to_d.f90 -I/usr/local/include -lfftw3
./a.out
cp out1.dat hzas$i.out 
cp out2.dat hzps$i.out
cp out3.dat hzfft$i.out
i=`expr $i + 10`
j=`expr $j + 10`
done