#!/bin/sh

#メインスクリプト::::::::::::::::::::::::::::::
#export OMP_NUM_THREADS=3


# CPML
ifort -o ficticious parameter.f90 set_condition.f90 waveform.f90 model.f90 output.f90 e_field4.f90 e_cpml4.f90 h_field4.f90 h_cpml4.f90 main2.f90 # -check all -CB -traceback -g

#Mur
 # ifort -o ficticious parameter.f90 set_condition.f90 waveform.f90 model.f90 output.f90 e_field4.f90 mur2.f90 h_field4.f90 main2.f90 # -check all -CB -traceback -g

#cerjan
# ifort -o ficticious parameter.f90 set_condition.f90 makewave.f90 model.f90 output.f90 e_field4.f90 cerjan.f90 h_field4.f90 main2.f90 #-check all -CB -traceback -g

time ./ficticious


#FFTスクリプト(H)::::::::::::::::::::::::::::::
# i=1010
# j=`expr $i - 1000`
# max=30

# while [ $j -le $max ]; do
# cp hz$i.d inp1.dat
# ifort -o fftw_hz ../code/parameter.f90 f_to_d.f90 -I/usr/local/include -lfftw3
# ./fftw_hz
# cp out1.dat ashz$i.out
# cp out2.dat pshz$i.out
# cp out3.dat ffthz$i.out
# i=`expr $i + 10`
# j=`expr $j + 10`
# done


# #FFTスクリプト(Jh)::::::::::::::::::::::::::::
# cp jh_fic.d inp1.dat
# ifort -o fftw_jh ../code/parameter.f90 f_to_d.f90 -I/usr/local/include -lfftw3 #-check all -CB -traceback -g
# ./fftw_jh
# cp out1.dat asjh.out
# cp out2.dat psjh.out
# cp out3.dat jh_dif.out


# #グリーン関数スクリプト(GEJ_in):::::::::::::::::::
# i=1010
# j=`expr $i - 1000`
# max=30

# cp jh_dif.out inp2.dat

# while [ $j -le $max ]; do
# cp ffthz$i.out inp1.dat
# ifort -o green ../code/parameter.f90 ../code/green.f90 -check all -CB -traceback -g
# ./green
# cp out1.dat Gej_x$i.out
# i=`expr $i + 10`
# j=`expr $j + 10`
# done



# #画像出力::::::::::::::::::::::::::::::::::::
# #ある点でのHZの時間分布
 # ./gnu.sh
# #HZの伝播movie
  # ./movie.sh