#!/bin/sh
date
#メインスクリプト::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# export OMP_NUM_THREADS=5

#構造改革
ifort -o ficticious_fwi_cpml parameter_wafe.f90 set_condition.f90 waveform.f90 model.f90 output.f90 eh_field_cpml42.f90 cpml4.f90 cerjan.f90 main2.f90 # -check all -CB -traceback -g -r8


# # all in
# ifort -o ficticious_fwd parameter.f90 set_condition.f90 waveform.f90 model.f90 output.f90 e_field_cpml4.f90 e_field4.f90 h_field_cpml4.f90 h_field4.f90 cpml.f90 mur2.f90 cerjan.f90 pml.f90 main2.f90 # -check all -CB -traceback -g -r8

# CPML
# ifort -o ficticious_cpml parameter.f90 set_condition.f90 waveform.f90 model.f90 output.f90 e_field4.f90 h_field4.f90 cpml.f90 main2.f90 # -check all -CB -traceback -g -r8

# Mur
 # ifort -o ficticious parameter.f90 set_condition.f90 waveform.f90 model.f90 output.f90 e_field4.f90 mur2.f90 h_field4.f90 main2.f90 # -check all -CB -traceback -g -r8

# cerjan
# ifort -o ficticious parameter.f90 set_condition.f90 waveform.f90 model.f90 output.f90 e_field4.f90 cerjan.f90 h_field4.f90 main2.f90 #-check all -CB -traceback -g -r8

# PML
# ifort -o ficticious parameter.f90 set_condition.f90 waveform.f90 model.f90 output.f90 e_field4.f90 e_pml.f90 h_field4.f90 h_pml.f90 main2.f90 #-check all -CB -traceback -g -r8

time ./ficticious_fwi_cpml

# #画像出力::::::::::::::::::::::::::::::::::::
# #ある点でのH'zの時間分布
  sh gnu.sh
# #H'zの伝播movie
    # sh movie.sh



#DFT,IDFT,IFFTスクリプト(E)::::::::::::::::::::
cp jh_fic.d inp2.dat #source J'

i=1010
j=`expr $i - 1000`
max=30

while [ $j -le $max ]; do
cp ex$i.d inp1.dat #E'

ifort -o f_to_d parameter_wafe.f90 window_function.f90 f_to_d_e.f90 -lfftw3 #-check all -CB -traceback -g -r8  #-I/usr/local/include -lfftw3 #-check all -CB -traceback -g -r8
./f_to_d

cp out1.dat EX_w$i.dat
cp out2.dat JX_w$i.dat
cp out3.dat GX_w$i.dat
cp invGE.dat EX_t$i.dat
cp invGJ.dat JX_t$i.dat
cp invGG.dat GX_t$i.dat
i=`expr $i + 10`
j=`expr $j + 10`
done

rm out*.dat invG*.dat



python subplot.py
#DFT,IDFT,IFFTスクリプト(H)::::::::::::::::::::::::::::::
# cp jh_fic.d inp2.dat #source J'

# i=1010
# j=`expr $i - 1000`
# max=30

# while [ $j -le $max ]; do
# cp Hz$i.d inp1.dat #H'

# ifort -o f_to_d parameter_wafe.f90 taper.f90 f_to_d_h.f90 -lfftw3 -check all -CB -traceback -g -r8
# ./f_to_d

# cp out1.dat HZ_w$i.dat
# cp out2.dat JX_w$i.dat
# cp out3.dat GX_w$i.dat
# cp invGH.dat HZ_t$i.dat
# cp invGJ.dat JX_t$i.dat
# cp invGG.dat GX_t$i.dat
# i=`expr $i + 10`
# j=`expr $j + 10`
# done

# rm out*.dat invG*.dat









				# # #DFTスクリプト(Jh)::::::::::::::::::::::::::::
				# cp jh_fic.d inp1.dat
				# ifort -o fftw_jh ../code/parameter_wafe.f90 f_to_d.f90 -I/usr/local/include -lfftw3 #-check all -CB -traceback -g
				# ./fftw_jh
				# cp out1.dat asjh.out
				# cp out2.dat psjh.out
				# cp out3.dat jh_dif.out


#FFTスクリプト(H)::::::::::::::::::::::::::::::
# i=1010
# j=`expr $i - 1000`
# max=30

# while [ $j -le $max ]; do
# cp hz$i.d inp1.dat
# ifort -o parameter_wafe.f90 taper.f90 f_to_d2.f90 -lfftw3   #-I/usr/local/include -lfftw3
# ./fftw_hz
# cp out1.dat ashz$i.out
# cp out2.dat pshz$i.out
# cp out3.dat ffthz$i.out
# i=`expr $i + 10`
# j=`expr $j + 10`
# done
# rm out*.dat


# #FFTスクリプト(Jh)::::::::::::::::::::::::::::
# cp jh_fic.d inp1.dat
# ifort -o fftw_jh ../code/parameter_wafe.f90 f_to_d.f90 -I/usr/local/include -lfftw3 #-check all -CB -traceback -g
# ./fftw_jh
# cp out1.dat asjh.out
# cp out2.dat psjh.out
# cp out3.dat jh_dif.out


# #グリーン関数スクリプト(GEJ_in):::::::::::::::::::
# i=1010
# j=`expr $i - 1000`
# max=30

# cp jh_dif.out inp2.dat

# while [ $j -le $max ]; do
# cp ffthz$i.out inp1.dat
# ifort -o green ../code/parameter_wafe.f90 ../code/green.f90 -check all -CB -traceback -g
# ./green
# cp out1.dat Gej_x$i.out
# i=`expr $i + 10`
# j=`expr $j + 10`
# done


