double *grad, *grad_p;
double _Complex *Exobs;
double _Complex *Eyobs;
double _Complex *Ezobs;
double _Complex *rec_ex;
double _Complex *delEx_t;
double _Complex *delEx_f;
double _Complex *delEy_f;
double _Complex *delEz_f;
double _Complex *Ecal_f;
double _Complex *EcalX_b;
double _Complex *EcalY_b;
double _Complex *EcalZ_b;
double _Complex *EcalX_back;
double _Complex *EcalY_back;
double _Complex *EcalZ_back;
double _Complex *EcalX_bb;
double _Complex *EcalY_bb;
double _Complex *EcalZ_bb;
double _Complex *EcalX_ff,*EcalX_ff2,*EcalX_ffL,*EcalX_del;
double _Complex *EcalY_ff,*EcalY_ff2,*EcalY_ffL,*EcalY_del;
double _Complex *EcalZ_ff,*EcalZ_ff2,*EcalZ_ffL,*EcalZ_del;
double *Ex_backwave;
double *Gx_back;
double *sense;
double alpha,scaler;
double _Complex k1,k2;
FILE *ofer;
